import tkinter
win=tkinter.Tk()
win.title('Synnefo')
win.geometry=('300*300')
win.maxsize(400,400)
win.minsize(100,100)
win.config(background='aqua')

def data():
    l4=tkinter.Label(win)
    l4.pack()
    data=e1.get()
    data1=v1.get()
    data2=v2.get()
    print(data1)
    l4.config(text=data)
    
#Label Positioning
l1=tkinter.Label(win,text="Welcome")
l2=tkinter.Label(win,text="To")
l3=tkinter.Label(win,text="Python")
e1=tkinter.Entry(win,background='white',foreground='black')
e1.pack()
b1=tkinter.Button(win,background='blue',foreground='black',text='Submit',padx=5,pady=5,command=data)
b1.pack()
v1=tkinter.IntVar()
v2=tkinter.IntVar()
c1=tkinter.Checkbutton(win,variable=v1,text="sslc")
c1.pack()
c2=tkinter.Checkbutton(win,variable=v2,text="+2")
c2.pack()
v2=tkinter.IntVar()
# l1.grid(row=0,column=2)
# l2.grid(row=0,column=1)
# l3.grid(row=0,column=0)
# l1.pack()
# l1.place(x=20,y=30)
# l1.grid(row=2,column=3)
l1.config(background='Red')
l2.config(background='green')
l3.config(background='yellow')
win.mainloop()